name: Release Images

on:
  workflow_call:
    inputs:
      repository:
        description: 'Name of the repo to download files from'
        type: string
      run-id:
        description: 'Id of the run to download files from'
        type: string
      name:
        description: 'Artifact name to download'
        type: string

jobs:
   download-release:
      runs-on: ubuntu-latest
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.7
          with:
              repository: '${{ github.event.inputs.repository }}'
              run-id: '${{ github.event.inputs.run-id }}'
              name:  '${{ github.event.inputs.name }}'
              github-token: ${{ secrets.GITHUB_TOKEN }}
