name: CI Release Images

on:
  workflow_call:
    inputs:
      repository:
        description: 'Name of the repo to download server artifact from'
        type: string
      run-id:
        description: 'Id of the run to download server artifact from'
        type: string
      art-name:
         description: 'Artifact name to download'
         type: string
      name:
         description: 'file name to unzip, no extension'
         type: string
      tags:
        description: 'Tags for the image'
        type: string
  workflow_dispatch:
     inputs:
       repository:
         description: 'Name of the repo to download server artifact from'
         type: string
       run-id:
         description: 'Id of the run to download server artifact from'
         type: string
       art-name:
         description: 'Artifact name to download'
         type: string
       name:
         description: 'file name to unzip, no extension'
         type: string
      tags:
        description: 'Tags for the image'
        type: string

jobs:
   image:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
               repository: 'rigazilla/infinispan-images'
         - name: Download a Build Artifact
           uses: actions/download-artifact@v4.1.7
           with:
             repository: '${{ inputs.repository }}'
             run-id: '${{ inputs.run-id }}'
             name:  '${{ inputs.art-name }}'
             github-token: ${{ secrets.GITHUB_TOKEN }}

         - name: Install CEKit
           uses: cekit/actions-setup-cekit@v1.1.5

         - name: Create Dockerfile
           env:
             SERVER_ZIP: ${{ inputs.name }}.zip
           run: |
               pwd
               ls
               SERVER_OVERRIDE="{\"artifacts\":[{\"name\":\"server\",\"path\":\"${GITHUB_WORKSPACE}/${SERVER_ZIP}\"}]}"
               cekit -v --descriptor server-openjdk.yaml build --overrides '{'version': '${{ github.sha }}'}' --overrides ${SERVER_OVERRIDE} --dry-run docker

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Login to Quay
           uses: docker/login-action@v3
           with:
             registry: quay.io
             username: ${{ secrets.QUAY_USERNAME }}
             password: ${{ secrets.QUAY_TOKEN }}

         - name: Build
           uses: docker/build-push-action@v3
           with:
             context: ./target/image
             platforms: linux/amd64
             pull: true
             push: true
             file: target/image/Dockerfile
             tags: ${{ inputs.tags }}
             load: true
